export enum LostarkRegion {
  NORTH_AMERICA_EAST = "NORTH_AMERICA_EAST",
  NORTH_AMERICA_WEST = "NORTH_AMERICA_WEST",
  EUROPE_WEST = "EUROPE_WEST",
  EUROPE_CENTRAL = "EUROPE_CENTRAL",
  SOUTH_AMERICA = "SOUTH_AMERICA",
}
